# Generated by Django 3.0.5 on 2021-03-05 09:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('ID', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('USERNAME', models.CharField(max_length=50, unique=True)),
                ('PASSWORD', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('ID', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('HOST', models.CharField(max_length=200)),
                ('DISPLAY_NAME', models.CharField(max_length=200, unique=True)),
                ('URL', models.CharField(max_length=200)),
                ('GITHUB', models.CharField(max_length=200)),
                ('FOLLOWERS', models.ManyToManyField(blank=True, related_name='_author_FOLLOWERS_+', to='chat.Author')),
                ('FRIENDS', models.ManyToManyField(blank=True, related_name='_author_FRIENDS_+', to='chat.Author')),
                ('FRIEND_REQUESTS', models.ManyToManyField(blank=True, related_name='_author_FRIEND_REQUESTS_+', to='chat.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('COMMENT', models.TextField()),
                ('CONTENT_TYPE', models.CharField(max_length=200)),
                ('PUBLISHED', models.DateTimeField(default=django.utils.timezone.now)),
                ('AUTHOR', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chat.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('TITLE', models.TextField()),
                ('SOURCE', models.CharField(max_length=200)),
                ('ORIGIN', models.CharField(max_length=200)),
                ('DESCIPTION', models.TextField()),
                ('CONTENT_TYPE', models.CharField(max_length=200)),
                ('CONTENT', models.TextField()),
                ('CATEGORIES', models.CharField(max_length=200)),
                ('COMMENTS_NO', models.IntegerField()),
                ('PAGE_SIZE', models.IntegerField()),
                ('COMMENTS_FIRST_PAGE', models.CharField(max_length=200)),
                ('PUBLISHED', models.DateTimeField(default=django.utils.timezone.now)),
                ('VISIBILITY', models.CharField(max_length=50)),
                ('UNLISTED', models.CharField(default='false', editable=False, max_length=50)),
                ('AUTHOR', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chat.Author')),
                ('COMMENTS', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='TIMELINE',
            field=models.ManyToManyField(blank=True, to='chat.Post'),
        ),
    ]
