# Generated by Django 3.0.5 on 2021-02-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
            ],
        ),
    ]
