# Generated by Django 3.0.5 on 2021-02-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='display_name',
            new_name='DISPLAY_NAME',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='host',
            new_name='GITHUB',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='id_str',
            new_name='HOST',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='url',
            new_name='ID',
        ),
        migrations.AddField(
            model_name='author',
            name='FOLLOWERS',
            field=models.ManyToManyField(related_name='_author_FOLLOWERS_+', to='chat.Author'),
        ),
        migrations.AddField(
            model_name='author',
            name='FRIENDS',
            field=models.ManyToManyField(related_name='_author_FRIENDS_+', to='chat.Author'),
        ),
        migrations.AddField(
            model_name='author',
            name='URL',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
