# Generated by Django 3.0.5 on 2021-03-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='COMMENTS',
        ),
        migrations.AddField(
            model_name='post',
            name='COMMENTS',
            field=models.ManyToManyField(blank=True, to='chat.Comment'),
        ),
    ]
