# Generated by Django 3.0.5 on 2021-03-01 07:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210221_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='AUTHOR',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='CATEGORIES',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='COMMENTS_FIRST_PAGE',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='COMMENTS_NO',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='CONTENT',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='CONTENT_TYPE',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='DESCIPTION',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='ID',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='ORIGIN',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='PAGE_SIZE',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='PUBLISHED',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='SOURCE',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='UNLISTED',
            field=models.CharField(default='false', editable=False, max_length=7),
        ),
        migrations.AddField(
            model_name='post',
            name='VISIBILITY',
            field=models.CharField(choices=[('public', 'Public'), ('friend', 'Friend')], default='public', max_length=6),
        ),
        migrations.AlterField(
            model_name='author',
            name='FOLLOWERS',
            field=models.ManyToManyField(blank=True, related_name='_author_FOLLOWERS_+', to='chat.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='FRIENDS',
            field=models.ManyToManyField(blank=True, related_name='_author_FRIENDS_+', to='chat.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('COMMENT', models.TextField()),
                ('CONTENT_TYPE', models.CharField(max_length=200)),
                ('PUBLISHED', models.DateTimeField()),
                ('AUTHOR', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chat.Author')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='COMMENTS',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.Comment'),
            preserve_default=False,
        ),
    ]
