# Generated by Django 2.1.7 on 2021-03-25 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('HOST', models.CharField(max_length=200, null=True)),
                ('DISPLAY_NAME', models.CharField(max_length=200, null=True, unique=True)),
                ('URL', models.CharField(max_length=200, null=True)),
                ('GITHUB', models.CharField(max_length=200, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('COMMENT', models.TextField()),
                ('CONTENT_TYPE', models.CharField(max_length=200)),
                ('PUBLISHED', models.DateTimeField(default=django.utils.timezone.now)),
                ('AUTHOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.CharField(default=uuid.uuid4, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('TITLE', models.TextField()),
                ('SOURCE', models.CharField(max_length=200)),
                ('ORIGIN', models.CharField(max_length=200)),
                ('DESCRIPTION', models.TextField()),
                ('CONTENT_TYPE', models.CharField(max_length=200)),
                ('CONTENT', models.TextField()),
                ('CATEGORIES', models.CharField(max_length=200)),
                ('COMMENTS_NO', models.IntegerField()),
                ('PAGE_SIZE', models.IntegerField()),
                ('COMMENTS_FIRST_PAGE', models.CharField(max_length=200)),
                ('PUBLISHED', models.DateTimeField(default=django.utils.timezone.now)),
                ('VISIBILITY', models.CharField(max_length=50)),
                ('UNLISTED', models.CharField(default='false', editable=False, max_length=50)),
                ('AUTHOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('COMMENTS', models.ManyToManyField(blank=True, to='chat.Comment')),
            ],
        ),
    ]
