# Generated by Django 2.1.7 on 2021-04-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
